apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clinic-appointment-ingress
  namespace: clinic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: clinic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clinic-appointment-system
                port:
                  number: 8090
