apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: clinic
  labels:
    app: mysql
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: clinic_db
  MYSQL_USER: clinic_user
  MYSQL_PASSWORD: clinic_password
